[package]
name = "wayland-client"
version = "0.1.0"
edition = "2021"

build = "../codegen/etc/build.rs"

[dependencies]
emacs-sys = { path = "../emacs-sys", features = ["window-system-wlc"] }
webrender = { path = "../webrender", default-features = false, features = ["window-system-wlc", "surfman"] }

[build-dependencies]
codegen = { path = "../codegen" }

[features]
default = ["surfman"]
glutin=["webrender/glutin"]
surfman=["webrender/surfman"]
capture=["webrender/capture"]
profiling=["webrender/profiling"]
sw_compositor=["webrender/sw_compositor"]
