[package]
name = "wr"
description = "Emacs draw api using Rust crate webrender"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["staticlib"]
path = "src/lib.rs"

[dependencies]
emacs-sys = { path = "../emacs-sys", features = ["webrender"] }
log.workspace = true
libc.workspace = true
gleam.workspace = true
image.workspace = true
bit-vec = "0.6.3"
raw-window-handle.workspace = true
euclid.workspace = true
parking_lot.workspace = true
webrender = { workspace = true }
wr_glyph_rasterizer.workspace = true
rayon = "1"
tracing = "0.1"

[dependencies.tracing-subscriber]
version = "0.3"
features = [
  "matchers",
  "regex",
  "once_cell",
  "tracing",
  "std",
  "thread_local",
  "env-filter"
]

[build-dependencies]
anyhow = "1"
cfg_aliases.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9"

[features]
default=["window-system-wlc", "surfman"]
window-system-pgtk=["emacs-sys/window-system-pgtk", "gtk3", "emacs-sys/webrender"]
window-system-wlc=["emacs-sys/window-system-wlc", "emacs-sys/webrender"]
glutin=["emacs-sys/glutin"]
surfman=["emacs-sys/surfman"]
gtk3=["emacs-sys/gtk3"]
capture=["webrender/capture", "webrender/serialize_program"]
profiling=["webrender/profiler"]
sw_compositor=["webrender/sw_compositor"]
